name: UTroll
version: 1.1
main: utroll.UTroll
api-version: 1.21
author: UTroll
softdepend:
  - ProtocolLib

commands:
  troll:
    description: Тролль команды
    usage: /troll <nick> <action>
    permission: utroll.troll

permissions:
  utroll.troll:
    description: Позволяет использовать команды тролля
    default: op
